#all: main
all: test
#main: main.cpp 
#	g++ main.cpp -o main -lm -O2 -DONLINE_JUDGE -fno-elide-constructors -std=c++11

test: test.cpp
	g++ test.cpp -o main -lm -O2 -DONLINE_JUDGE -fno-elide-constructors -std=c++11

clean:
	rm *.o main
